### ISSUE TITLE
UDP基础通信时，A发送一包给B，B会收到两次。

### ISSUE THREAD

**Issue by h1t2y3g4** [Zhou-zhi-peng/NetDebugger#10]
UDP基础通信，同一台电脑开两个程序，或者是放到两台不同的电脑上。均会出现一个发送了一次数据，另一个却接收到了两次的情况。
然而我用野火多功能调试助手就没有出现这种情况。
用wireshark抓包看，确实用此程序发送时，会收到两包UDP包。而野火的只会收到一包。

**Comment by solaris111** [comment]
我没发现这个问题，这个在IPV6调试UDP报文时及其好用

**Comment by Zhou-zhi-peng** [comment]
![image](https://user-images.githubusercontent.com/39650177/167323647-d7d55d80-a33a-4d8e-9a08-1fda75dcc97e.png)
这是因为UDP基础通信中首先会按配置的服务器地址建立一个通道，一但有其它UDP端之通讯时建立自动一个相 关通道，如果不选择通道，则会多个通道一起发送，则会出现你描述的情况。
之所以这么设计，是因为UDP可以在只绑定自己的地址情况下，让其它UDP与其通讯，此时接收端可以获取到发送端地址，通过这个地址发送数据，为方便接收端可以快速向发送端回复数据，而不用重新绑定，因此设计成多通道的。

**Comment by Zhou-zhi-peng** [comment]
![image](https://user-images.githubusercontent.com/39650177/167324517-6eaef94a-9a5f-45d4-86de-9cbcc51bb975.png)
但是，这个功能可以优化一下，当检测到收发双方完全一致的通道存在时，可以不用再将建立通。这样可以更好的提升使用体验。在下次发版时，会增加该优化。

**Comment by h1t2y3g4** [comment]
> ![image](https://user-images.githubusercontent.com/39650177/167323647-d7d55d80-a33a-4d8e-9a08-1fda75dcc97e.png) 这是因为UDP基础通信中首先会按配置的服务器地址建立一个通道，一但有其它UDP端之通讯时建立自动一个相 关通道，如果不选择通道，则会多个通道一起发送，则会出现你描述的情况。 之所以这么设计，是因为UDP可以在只绑定自己的地址情况下，让其它UDP与其通讯，此时接收端可以获取到发送端地址，通过这个地址发送数据，为方便接收端可以快速向发送端回复数据，而不用重新绑定，因此设计成多通道的。

感谢您的指导！选择特定通道就好了。那么感觉这个功能还是有点用。或许只需要在readme里面提示一下就行了，不需要阉割掉此功能。
