### ISSUE TITLE
关于websocket header key大小写问题

### ISSUE THREAD

**Issue by giiiiiithub** [Zhou-zhi-peng/NetDebugger#13]
你好，非常感谢作者的软件，很好用。

但是在使用websocket server功能时，发现client握手失败。究其原因是我这边client（使用某个库）的请求header key全都是小写，而server这边全是以单词首字母大写key从headers中取值。

比如：我的client发起请求Header key有：sec-websocket-key，但是在您这边使用的Key是: Sec-WebSocket-Key，这就会导致取不到值转而使用了默认置，致使Sec-WebSocket-Accept计算错误。

我翻了一下[rfc6455](https://datatracker.ietf.org/doc/html/rfc6455#section-4.2)，其中20页有这么一句：

`Please note that according to [[RFC2616](https://datatracker.ietf.org/doc/html/rfc2616)], all header field names in
   both HTTP requests and HTTP responses are case-insensitive.`

header filed name是大小写不敏感的。

**Comment by Zhou-zhi-peng** [comment]
这是一个BUG，待我修复一下。

**Comment by Zhou-zhi-peng** [comment]
问题已经修复。

**Comment by giiiiiithub** [comment]
> 问题已经修复。

好像是没权限，这个咋弄？

![image](https://user-images.githubusercontent.com/74041961/172091674-a8e3cd55-c195-4961-ae58-2d5f3275c27d.png)

**Comment by Zhou-zhi-peng** [comment]
权限?具体指的是什么问题？

**Comment by Zhou-zhi-peng** [comment]
刚才图没显示出来，我试一下，我这本地是可以的，所以你遇到的问题可能是以下两个原因造成的：
1、端口被占用了（从截图上来看，这种可能性比较高）
2、防火墙或杀毒软件阻止程序进行网络监听

**Comment by giiiiiithub** [comment]
> 刚才图没显示出来，我试一下，我这本地是可以的，所以你遇到的问题可能是以下两个原因造成的： 1、端口被占用了（从截图上来看，这种可能性比较高） 2、防火墙或杀毒软件阻止程序进行网络监听

 是的，感谢
