### ISSUE TITLE
串口默认参数波特率0时会触发驱动崩溃蓝屏

### ISSUE THREAD

**Issue by Mo-Yuxi** [Zhou-zhi-peng/NetDebugger#17]
软件第一次启动时，串口相关默认设置的波特率为0，当未调节该参数就直接进行连接串口会在Windows端发生崩溃蓝屏

**Comment by Zhou-zhi-peng** [comment]
你应该是用的是USB或其它方式的虚拟串口，而该虚拟串口的驱动实现不太完善，对错误的参数没有校验，从而导致了内核崩溃。
强烈建议不要使用未经过微软认证的内核驱动。
NetDebugger本身是应用层软件，不会直接导致系统崩溃。

**Comment by Mo-Yuxi** [comment]
经检查确实为USB-TTL驱动存在问题，本问题出现在CH340的USBTTL驱动上。当时使用两块CH340连接到PC，使PC转发这两个串口的数据给对方，进而实现监听。在更新到较新版本的带有微软数字签名认证的CH340驱动后问题不再出现
